### ISSUE TITLE
Add CI/CD Pipeline with Github Actions

### ISSUE THREAD

**Issue by mpiannucci** [asascience-open/xarray-subset-grid#11]
Should build for all python version > 3.9 across Windows, Linux, and Mac

**Comment by ChrisBarker-NOAA** [comment]
What do you think about code linting / etc?

I find it annoying for code to have pass a lint in order for the pipeline not to fail, but others like it :-)

And you are using black, yes?

**Comment by mpiannucci** [comment]
I have been using [ruff](https://docs.astral.sh/ruff/) instead of black. I tend to like lints as long as they are basic and not overly restrictive

**Comment by ChrisBarker-NOAA** [comment]
The CI is in place, but only for running the tests.

If we want to add any of:
- Linting
- Coverage
- Type checking

That can be done. 

I've some experience with linting (though not with ruff) and coverage, but none with type checking[*] -- thoughts on that?

New issue for these? 

[*] To be frank, I'm a "typing skeptic" Im not convinced it helps more than it hinders a project. But that seems to be the way folks are going, and there are type hints in the code now (which I've been trying to maintain).

However, it's probably a "bad idea" to have type hints in the code, and not be running a type checker on it regularly. Incorrect type hints are worse than no type hints!
