### ISSUE TITLE
Add Vertical Subsetting abstract methods and UGRID/SGRID implementations

### ISSUE THREAD

**Issue by mpiannucci** [asascience-open/xarray-subset-grid#17]
Many times, datasets need to be subset in vertical space. Vertical coordinates may or may not be related to the actual underlying grid system.

**Comment by mpiannucci** [comment]
@ChrisBarker-NOAA Do you have any input for this? Most of the datasets have sigma coordinates. 

The simplest way to do this is just allow the user to pass in the sigma levels they want? Or does it make more sense to design around sigma indexes?

**Comment by ChrisBarker-NOAA** [comment]
In practice the most common use is one of:
  - "just the surface" -- or *maybe* "just the bottom"
  - the whole depth (fully 3d)

So I think being able to specify a sigma level(s) is good.

Ideally you could specify "surface" or "bottom", and let the code figure out if that's the first or last index.

**Comment by mpiannucci** [comment]
Okay so thinking we add minimum two methods: 

`vertical_levels`: Returns a list of the available vertical levels 

`subset_vertical_levels`: slices and returns only the selected layer or layers
