### ISSUE TITLE
Python version support.

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [asascience-open/xarray-subset-grid#24]
This may be a time to think about minimum Python version:

As this is a new project, I'm thinking being forward thinking -- 3.10+ maybe?

3.9 will be supported through most of  2025 -- but 3.10 has been out for a few years, and 3.12 is the latest production version. I'd think 3.10, 3.11, 3.12 would be enough for now.

The less we're doing to support older versions, the better -- see  #21

**Comment by mpiannucci** [comment]
I agree 3.9 has significant differences and would be happy not to support it

**Comment by ChrisBarker-NOAA** [comment]
Done -- in pyproject.toml and CI: 71e416d685db2a40
