### ISSUE TITLE
Fully commit to CF compliance?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [asascience-open/xarray-subset-grid#26]
It seems the design philosophy here is that the core functionality is based on CF-compliant datasets.

If a dataset is not CF compliant, then we provide utilities to make it CF compliant (and/or require the provider to do that themselves first).

I think this simplifies the code, and makes it more robust -- if the heuristics used to find something fail, it will fail at the "make it CF compliant" stage, not the "use it" stage.

I haven't audited the code to see where this might not be done already -- but one place that needs updating is the `data_vars` code.

(and of course, the `assign_ugrid_topology` utility, which is not complete -- in particular, there's no addition of metadata to the data variables

https://ugrid-conventions.github.io/ugrid-conventions/#data-defined-on-unstructured-meshes

which should have `mesh` and `location` attributes:

```
double Mesh2_waterlevel(time,nMesh2_face) ;
    Mesh2_waterlevel:standard_name = "sea_surface_height_above_geoid" ;
    Mesh2_waterlevel:units = "m" ;
    Mesh2_waterlevel:mesh = "Mesh2"
    Mesh2_waterlevel:location = "face" ;
    Mesh2_waterlevel:coordinates = "Mesh2_face_x Mesh2_face_y" ;
```

**Comment by mpiannucci** [comment]
In theory they should.... but almost no datasets include this so i targeted the middle ground in the beginning. We can add functions to add that metadata as an option though since we can already detect via xarray dimensions.

**Comment by ChrisBarker-NOAA** [comment]
Yeah, as far as I know, there are pretty much no properly compliant datasets in the wild.

So we need to accommodate non-compliant files -- but where? So far, I"ve seen (and written) a lot of code that used heuristics / makes assumnptions in the middle of the code, where the information is used. But I regret that -- it:

a) makes it very hard to locate the errors / fixes when it doesn't work.
b) makes the code fail late, rather than early
c) provides not encouragement to others to make their files compliant.

So I'm thinking that any "make it compliant" or "guess what things mean" code should be outside of the core, and strictly a pre-processing step, that users opt-in to.

**Comment by ChrisBarker-NOAA** [comment]
I *think* that we're heading that way now -- with the check for `start_index` in the subsetting code, I don't think there are any other heuristics/assumptions in the core code.

@mpiannucci: if you agree, we can close this.

**Comment by ChrisBarker-NOAA** [comment]
NOTE: I've added #39 -- if we get to it.

**Comment by mpiannucci** [comment]
The last piece of this is handling the face dimensions i think. Then we can close this out. Also have to see what pieces are missing for schism

**Comment by mpiannucci** [comment]
Moved to #39
