### ISSUE TITLE
make data_vars, grid_vars, etc a set?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [asascience-open/xarray-subset-grid#28]
It seem these really are sets -- e.g. order doesn't matter.

ANd currently we are converting back and forth between lists and sets for no good reason.

Why not just have them be sets?

They's still be iterable, and sized, and ... the only thing you couldn't do is index them, but why would anyone want to do that?

**Comment by ChrisBarker-NOAA** [comment]
Note: xarray.data_vars is a special `DataVariables` -- not a list -- and looks lmore like a dict than a list. 

I don't know that we need the dict interface, but a set could work well.

**Comment by mpiannucci** [comment]
Set works for me

**Comment by ChrisBarker-NOAA** [comment]
Done in: 2474edf2f02b10
