### ISSUE TITLE
Support zero and one based indexing:

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [asascience-open/xarray-subset-grid#32]
The UGRID spec allows either zero-based (C-style) or one-based(Fortran style) indexing:

https://ugrid-conventions.github.io/ugrid-conventions/#zero-or-one-based-indexing

This code should be checking the start_index attribute, and using that whenever required.

Right now, I see code that assumes 1-based:

UGrid.subset_polygon: line 130.

`tris = ds[mesh.face_node_connectivity].T - 1`

This is dangerous -- particularly as the default is zero-based!

As with everything else, the code at that point should check that attribute -- if it's not there, it should be added by pre-processing code.

**Comment by ChrisBarker-NOAA** [comment]
If there's a default, it should be zero -- that's what the UGRID spec says. 

Fortunately, you can usually figure it out -- if there's a zero in the index arrays, then it's zero-indexed.

For this code, I think we should use the "start_index" attribute, and in the "add CF compliance metadata" function, guess at that value, if it's not there.

**Comment by ChrisBarker-NOAA** [comment]
Added the start_index attribute in #37

**Comment by mpiannucci** [comment]
@mpiannucci add the code using the start_index into the ugrid subsetting logic
