### ISSUE TITLE
subsetting loses the time variable encoding

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [asascience-open/xarray-subset-grid#36]
if you point to a dataset with a time variable (encoded with the CF conventions), it gets the encoding info:

```
ds['time'].encoding

{'chunks': (787,),
 'preferred_chunks': {'time': 787},
 'compressor': Zstd(level=1),
 'filters': None,
 'units': 'seconds since 2018-01-01 00:00:00',
 'dtype': dtype('float64')}
```
But after calling subset:

```
ds_subset = ds.subset_grid.grid.subset_bbox(ds, bounds)

ds_subset['time'].encoding
{}
```
the time variable has lost the encoding info.

This is a problem, because then when you call `to_netcdf()`, the time gets encoded in nanoseconds (the pandas datetime64 default) -- which most software can't deal with, so *boom*.

if you copy the encoding before subsetting, and then put it back, it seems to work fine, so that's probably what needs to be done.

Sorry -- no time to write a test right now ...

**Comment by mpiannucci** [comment]
Good catch! Should be easy enough to fix

**Comment by mpiannucci** [comment]
The notebooks seem to keep working if i get rid of the encoding drop, I cannot remember why i had to add it in the first place  so trying to backtrace myself

**Comment by ChrisBarker-NOAA** [comment]
Great, thanks. Can we close this?
