### ISSUE TITLE
Kerchunking turns a integer attribute to a string.

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [asascience-open/xarray-subset-grid#43]
This isn't the right place for this, as it's not this code that's doing it, but I wasn't sure what else to post.

But:

When we point to a kerchunked version of the WCOFS model on aws, a varible attribute that is oringinaly an integer (2) becomes a string ("2") -- which then breaks some downstream tools.

Example:

```
fs = fsspec.filesystem(
    "reference",
    fo="s3://nextgen-dmac-cloud-ingest/nos/wcofs/nos.wcofs.2ds.best.nc.zarr",
    remote_protocol="s3",
    remote_options={"anon": True},
    target_protocol="s3",
    target_options={"anon": True},
)
m = fs.get_mapper("")

ds = xr.open_dataset(
    m, engine="zarr", backend_kwargs=dict(consolidated=False), chunks={})

print(ds.grid.attrs['topology_dimension'])
print(type(ds.grid.attrs['topology_dimension']))
```
```
2
<class 'str'>
```
If you download the WFCOFS files directly from AWS, and open them in xarray, that attribute is a integer.

NOTE: while most netcdf variable attributes are strings, the can be (I think) any data type -- including arrays.

" A netCDF attribute has a netCDF variable to which it is assigned, a name, a type, a length, and a sequence of one or more values. "

**Comment by mpiannucci** [comment]
This is a bug in our ingest I think so something we can fix pretty easily

**Comment by mpiannucci** [comment]
Okay I just tested with a newer version of the dataset and it is correct... can you try pointing at `[nos.wcofs.2ds.best.nc.zarr](s3://noaa-nodd-kerchunk-pds/nos/wcofs/wcofs.2ds.best.nc.zarr)`

**Comment by mpiannucci** [comment]
This is this all set so closing out. Let me know if the new file still has this issue
