### ISSUE TITLE
Change xarray accessor to `xsg`

### ISSUE THREAD

**Issue by mpiannucci** [asascience-open/xarray-subset-grid#46]
`subset_grid` is not great to typeout and `xsg` makes much more sense imo

**Comment by ChrisBarker-NOAA** [comment]
Good call -- and better to change now than later.

Are you going to keep an alias? or should we just updated all. the examples, etc and be done with it?

**Comment by mpiannucci** [comment]
I just updated it all, so were done with it before there are any actual other users
