### ISSUE TITLE
Documentation Setup

### ISSUE THREAD

**Issue by omkar-334** [asascience-open/xarray-subset-grid#58]
Currently the documentation is built upon my fork of this repository.  
To build it upon the main branch,   

1. Go to [ReadTheDocs](https://about.readthedocs.com/?ref=readthedocs.com)  
2. Sign up -> Community
3. Sign up using Github (Make sure to sign in with the `asascience-open` account  
This is important to give access to the repository
4. Import project
5. Enter project name and branch name
6. Finish -> Build version

Successfully setup!

**Comment by omkar-334** [comment]
To add a new example in the documentation, make sure the notebook / python file is in `docs/examples` folder.    
In `docs/notebooks.rst` , Add a new line at the end - ` examples/sample.ipynb`.  
Make sure that the notebook has a #heading so that it is rendered as the title for the example notebook

**Comment by mpiannucci** [comment]
Can you take down your version? Currently i cannot publish it because the name is taken

**Comment by omkar-334** [comment]
Sorry. I've deleted my project I think it should work now

**Comment by mpiannucci** [comment]
All set thank you!
