### ISSUE TITLE
Reuse Selector

### ISSUE THREAD

**Issue by omkar-334** [asascience-open/xarray-subset-grid#59]
I have added a name and location identifier to the selector class.  
The `location` attribute is automatically set using the polygon coordinates using hashing
![image](https://github.com/user-attachments/assets/2de2052e-5d68-4770-8093-ff091286eb77)

The `name` attribute is set during `compute_polygon_subset_selector` function.

For a user, to identify if the current location has already been computed and saved before, should we save the pickle file as `{self._location}.pkl` or `{self._name}.pkl` or a combination of both?

**Comment by omkar-334** [comment]
```
def compute_polygon_subset_selector(
        self, ds: xr.Dataset, polygon: list[tuple[float, float]], name: str = None
    ) -> Selector:
  ```  
  Here, we check if the polygon or name have been computed before. If yes, then load the pickle file and return selector.
  If no, then compute the selector and return it.  
  
In addition to this, I've added an explicit class method to load the selector.
Is this the right approach? @mpiannucci

**Comment by ChrisBarker-NOAA** [comment]
> {self._location}.pkl or {self._name}.pkl or a combination of both?

I would say both -- maybe: 

" {self._name}_{self._location}.pkl"

The name is presumably human-readable, and the location hash is unique.

if the file name gets too long, you could use only the first 10 chars or so of the hash -- not guaranteed to be unique, but pretty darn close.
