### ISSUE TITLE
Add ADCIRC Compatibility

### ISSUE THREAD

**Issue by mpiannucci** [asascience-open/xarray-subset-grid#9]
ADCRIC datasets should be compatible with the UGRID accessor, but to ensure this is so we need to test, and fix any issues that arise. This issue also covers adding example notebooks and test cases for ADCRIC datasets

**Comment by AtiehAlipour-NOAA** [comment]
Description:
This issue serves as a general ticket for the development of a subsetting tool for STOFS 2D model outputs. The aim is to add functionality to xarray-subset-grid code for efficiently subsetting data from STOFS 2D outputs while preserving key features of the model.

This issue serves as a starting point for the development of the subsetting tool. Subsequent issues may be created for smaller tasks related to its development.

For [STOFS-2D](https://noaa-gestofs-pds.s3.amazonaws.com/index.html), we use ADCIRC as the base model.

**Comment by mpiannucci** [comment]
ADCIRC is supported now AFAIK so i am going to close out this issue
